env:
  es2021: true
  browser: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module

settings:
  react:
    version: '18'

plugins:
  - react
  - react-hooks
  - eslint-plugin-tsdoc

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:you-dont-need-lodash-underscore/compatible
  - plugin:@typescript-eslint/recommended
  - plugin:storybook/recommended
  - plugin:tailwindcss/recommended
  - plugin:@next/next/recommended

rules:
  tailwindcss/no-custom-classname:
    - error
    - whitelist:
        [
          'autocomplete',
          'bg-grey/10',
          'translate-y-negative-1/2',
          'line-clamp-1',
          'line-clamp-2',
          'line-clamp-3',
          'line-clamp-4',
          'text-blue',
          'bg-grey-light',
          'bg-blue',
        ]
  react-hooks/exhaustive-deps:
    - error
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  no-console:
    - error
    - allow:
        - warn
        - error
  arrow-parens:
    - error
    - always
  no-else-return:
    - error
    - allowElseIf: false
  jsx-quotes:
    - error
    - prefer-double
  max-params:
    - error
    - 10
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true
  import/no-unresolved:
    - off
  import/no-default-export:
    - off
  '@typescript-eslint/explicit-function-return-type':
    - off
  'import/no-cycle':
    - error
